
server:
  port: 8090

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.133.238.253:3306/blog?timezoneService=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: RYAN
    password: ENC(4YHVX0u2ViD2RiKdIA8PZhrxGC/8tX6c)

  mvc:
    view:
      suffix: .html

  thymeleaf:
    cache: true
  redis:
    host: 101.133.238.253
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: ENC(Wte1zHjWbbZPFCV/BlkjOSXGVlIf1lH5)


logging:
  level:
    com.Ryan.Blog: warn
    org.springframework: warn
mybatis:
      type-aliases-package: com.Ryan.Blog.pojo
      mapper-locations: classpath:Ryan/Blog/mapper/*.xml
#      configuration:
#          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jasypt:
  encryptor:
    password: JHDAYWNAafwsww
