#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/yang?timezoneService=Asia/Shanghai
#  username: root
#  password: root

server:
  port: 8090


spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.133.238.253:3306/blog?timezoneService=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/m_blog?timezoneService=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: RYAN
    password: 182500yyC@

  mvc:
    view:
      suffix: .html

  thymeleaf:
    cache: false


logging:
  level:
    com.Ryan.Blog: info
    org.springframework: info
mybatis:
      type-aliases-package: com.Ryan.Blog.pojo
      mapper-locations: classpath:Ryan/Blog/mapper/*.xml
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
